global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'autocare360'
    environment: 'production'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "alert_rules.yml"

scrape_configs:
  - job_name: 'autocare360-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['app:8080']
        labels:
          application: 'autocare360'
          environment: 'production'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']
        labels:
          database: 'mysql'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          cache: 'redis'
