global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['autocare360-backend:8080']
        labels:
          application: 'autocare360-backend'
          environment: 'production'
