apiVersion: v1
kind: Service
metadata:
  name: autocare360-service
  labels:
    app: autocare360
spec:
  type: ClusterIP
  selector:
    app: autocare360
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
