apiVersion: v1
kind: ConfigMap
metadata:
  name: autocare360-config
  namespace: autocare360
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_URL: "jdbc:mysql://mysql-service:3306/autocare360?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
  CORS_ALLOWED_ORIGINS: "https://autocare360.vercel.app,http://localhost:3000"
  SERVER_PORT: "8080"
