name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Make mvnw executable (Unix)
      if: runner.os != 'Windows'
      run: chmod +x mvnw
    
    - name: Build with Maven
      run: ./mvnw clean compile
    
    - name: Run tests
      run: ./mvnw test
    
    - name: Generate test report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Maven Tests
        path: target/surefire-reports/*.xml
        reporter: java-junit
        fail-on-error: true
    
    - name: Upload test coverage
      if: success()
      uses: codecov/codecov-action@v4
      with:
        files: ./target/site/jacoco/jacoco.xml
        flags: unittests
        fail_ci_if_error: false