name: Deploy to Dev

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Make mvnw executable
      run: chmod +x mvnw
    - name: Build with Maven
      run: ./mvnw clean package -DskipTests
    - name: Run Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'Autocare360 Backend'
        path: '.'
        format: 'ALL'
        out: 'reports'
    - name: Build Docker image
      run: docker build -f infra/docker/Dockerfile -t autocare360-backend:dev .
    - name: Deploy to Dev Environment
      run: echo "Deploy to dev environment"  # Add actual deployment steps