name: Deploy to Prod

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: ./mvnw clean package -DskipTests
    - name: Build Docker image
      run: docker build -f infra/docker/Dockerfile -t autocare360-backend:latest .
    - name: Deploy to Prod Environment
      run: echo "Deploy to prod environment"  # Add actual deployment steps